### ISSUE TITLE
No limit for claiming

### ISSUE THREAD

**Issue by CupidonSauce173** [poggit-orphanage/FactionsPro_1.4#12]
Hi, I do not know if this is an issue but there is no limit on how much plots you can claim..

**Comment by Awzaw** [comment]
If you /f claim a second plot doesn't it just replace the first?

**Comment by CupidonSauce173** [comment]
no, sorry for the super late reply.

**Comment by Awzaw** [comment]
Here's after claiming a fac called myfac:
<img width="754" alt="screen shot 2018-06-06 at 21 17 36" src="https://user-images.githubusercontent.com/10437212/41060317-8ce278d6-69cf-11e8-8394-27ca3d06eaf5.png">
And here's what happens when I type /f claim somewhere else:
<img width="752" alt="screen shot 2018-06-06 at 21 20 10" src="https://user-images.githubusercontent.com/10437212/41060341-a34ec016-69cf-11e8-9fdc-c8edc46d7b37.png">
What do you see in your database?

**Comment by CupidonSauce173** [comment]
Oh ok sorry. I just saw it, this is an idea but it could be good to ask the owner of a faction to block the /f claim command if the owner of a faction own already a plot and asking him to do /f unclaim before claiming another plot. Just an idea.

**Comment by CupidonSauce173** [comment]
And just to know, is there a way to connect the plugin to a MySQL server ?

**Comment by Awzaw** [comment]
cf. https://forums.pmmp.io/threads/factionspro-and-mysql.5812/#post-51791

**Comment by CupidonSauce173** [comment]
@awzaw ?
